const duLieuDuAn = [
    {
        id: 1,
        title: 'Phát triển Website',
        start: new Date(2024, 2, 10, 9, 0),
        end: new Date(2024, 2, 10, 17, 0),
        desc: 'Tạo một trang web cho công ty',
        color: 'blue',
        tipo: 'Dự án',
    },
    {
        id: 2,
        title: 'Báo cáo Kết quả Doanh thu',
        start: new Date(2024, 3, 5, 10, 0),
        end: new Date(2024, 3, 5, 12, 0),
        desc: 'Chuẩn bị báo cáo cho cuộc họp hội đồng quản trị',
        color: '#f15550',
        tipo: 'Báo cáo',
    },
    {
        id: 3,
        title: 'Hội thảo Đổi mới Sáng tạo',
        start: new Date(2024, 4, 20, 14, 0),
        end: new Date(2024, 4, 20, 16, 0),
        desc: 'Tổ chức hội thảo về đổi mới sáng tạo trong doanh nghiệp',
        color: 'green',
        tipo: 'Sự kiện',
    },
    {
        id: 4,
        title: 'Đào tạo Nhân viên mới',
        start: new Date(2024, 5, 15, 10, 0),
        end: new Date(2024, 5, 15, 12, 0),
        desc: 'Đào tạo cho nhân viên mới về quy trình làm việc',
        color: 'purple',
        tipo: 'Đào tạo',
    },
    {
        id: 5,
        title: 'Tổ chức Sự kiện Ra mắt Sản phẩm',
        start: new Date(2024, 6, 30, 18, 0),
        end: new Date(2024, 6, 30, 21, 0),
        desc: 'Tổ chức sự kiện để giới thiệu sản phẩm mới ra thị trường',
        color: 'orange',
        tipo: 'Sự kiện',
    },
    {
        id: 6,
        title: 'Phân tích Thị trường',
        start: new Date(2024, 7, 25, 15, 0),
        end: new Date(2024, 7, 25, 17, 0),
        desc: 'Thực hiện phân tích thị trường để xác định cơ hội kinh doanh',
        color: 'cyan',
        tipo: 'Nghiên cứu',
    },
    {
        id: 7,
        title: 'Họp Đánh giá Hiệu suất',
        start: new Date(2024, 8, 1, 14, 0),
        end: new Date(2024, 8, 1, 16, 0),
        desc: 'Họp để đánh giá hiệu suất làm việc của nhân viên',
        color: 'pink',
        tipo: 'Họp',
    },
    {
        id: 8,
        title: 'Chuẩn bị Đề án Kinh doanh',
        start: new Date(2024, 9, 10, 10, 0),
        end: new Date(2024, 9, 10, 12, 0),
        desc: 'Chuẩn bị đề án cho dự án khởi nghiệp',
        color: 'brown',
        tipo: 'Dự án',
    },
    {
        id: 9,
        title: 'Giải quyết Vấn đề Khách hàng',
        start: new Date(2024, 10, 15, 9, 0),
        end: new Date(2024, 10, 15, 11, 0),
        desc: 'Giải quyết khiếu nại của khách hàng về sản phẩm',
        color: 'lime',
        tipo: 'Khách hàng',
    },
    {
        id: 10,
        title: 'Tổng kết Dự án Quý',
        start: new Date(2024, 11, 1, 20, 0),
        end: new Date(2024, 11, 1, 22, 0),
        desc: 'Tổng kết và đánh giá kết quả của dự án trong quý',
        color: 'teal',
        tipo: 'Báo cáo',
    },
    {
        id: 11,
        title: 'Đánh giá Rủi ro Dự án',
        start: new Date(2024, 11, 20, 12, 0),
        end: new Date(2024, 11, 20, 14, 0),
        desc: 'Thực hiện đánh giá rủi ro cho các dự án hiện tại',
        color: 'maroon',
        tipo: 'Nghiên cứu',
    },
    {
        id: 12,
        title: 'Hội nghị Khách hàng',
        start: new Date(2024, 11, 28, 16, 0),
        end: new Date(2024, 11, 28, 18, 0),
        desc: 'Tổ chức hội nghị để giao lưu và trao đổi với khách hàng',
        color: 'olive',
        tipo: 'Sự kiện',
    },
    {
        id: 13,
        title: 'Thuyết trình Dự án',
        start: new Date(2024, 0, 15, 9, 0),
        end: new Date(2024, 0, 15, 11, 0),
        desc: 'Thuyết trình về tiến độ và kết quả dự án cho ban lãnh đạo',
        color: 'navy',
        tipo: 'Thuyết trình',
    },
    {
        id: 14,
        title: 'Phân tích Chi phí Dự án',
        start: new Date(2024, 1, 10, 14, 0),
        end: new Date(2024, 1, 10, 16, 0),
        desc: 'Thực hiện phân tích chi phí cho dự án hiện tại',
        color: 'silver',
        tipo: 'Nghiên cứu',
    },
    {
        id: 15,
        title: 'Thiết kế Logo Công ty',
        start: new Date(2024, 2, 5, 11, 0),
        end: new Date(2024, 2, 5, 13, 0),
        desc: 'Thiết kế logo cho thương hiệu mới',
        color: 'gold',
        tipo: 'Thiết kế',
    },
    {
        id: 16,
        title: 'Đánh giá Sự hài lòng của Khách hàng',
        start: new Date(2024, 3, 1, 10, 0),
        end: new Date(2024, 3, 1, 12, 0),
        desc: 'Thực hiện khảo sát để đánh giá sự hài lòng của khách hàng',
        color: 'indigo',
        tipo: 'Nghiên cứu',
    },
    {
        id: 17,
        title: 'Họp Đội Nhóm',
        start: new Date(2024, 4, 5, 15, 0),
        end: new Date(2024, 4, 5, 17, 0),
        desc: 'Thảo luận về kế hoạch và tiến độ công việc',
        color: 'crimson',
        tipo: 'Họp',
    },
    {
        id: 18,
        title: 'Chuẩn bị Kế hoạch Marketing',
        start: new Date(2024, 5, 10, 18, 0),
        end: new Date(2024, 5, 10, 20, 0),
        desc: 'Chuẩn bị kế hoạch marketing cho sản phẩm mới',
        color: 'darkgreen',
        tipo: 'Marketing',
    },
    {
        id: 19,
        title: 'Thực hiện Khảo sát Thị trường',
        start: new Date(2024, 6, 5, 9, 0),
        end: new Date(2024, 6, 5, 11, 0),
        desc: 'Thực hiện khảo sát thị trường để thu thập dữ liệu',
        color: 'darkorange',
        tipo: 'Nghiên cứu',
    },
    {
        id: 20,
        title: 'Lên Kế hoạch Sự kiện',
        start: new Date(2024, 7, 5, 20, 0),
        end: new Date(2024, 7, 5, 22, 0),
        desc: 'Lên kế hoạch cho sự kiện kỷ niệm công ty',
        color: 'darkred',
        tipo: 'Sự kiện',
    }
];

export default duLieuDuAn;