const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    EMAIL_LOGIN_SUCCESS: 'EMAIL_LOGIN_SUCCESS',
    EMAIL_LOGIN_FAILURE: 'EMAIL_LOGIN_FAILURE',
};


export default actionTypes